import {DatabaseSync} from 'node:sqlite';
import {randomBytes,createHash,randomUUID,randomInt} from 'node:crypto';
export class ServiceError extends Error {constructor(message,status=400){super(message);this.status=status;}}
export function koreanDay(now){return new Date(now+9*3600000).toISOString().slice(0,10);}
export function nextKoreanMidnight(now){return Date.parse(koreanDay(now)+'T00:00:00+09:00')+86400000;}
const digest=value=>createHash('sha256').update(value).digest('hex');
function defaultDraw(){return Array.from({length:3},()=>{const rarityRoll=randomInt(100),rarityOffset=rarityRoll<70?1:rarityRoll<95?2:3;const conceptIndex=randomInt(32);return `E${String(conceptIndex*3+rarityOffset).padStart(3,'0')}`;});}
export class Ledger {
 constructor(path,{clock=Date.now,draw=defaultDraw}={}){this.clock=clock;this.draw=draw;this.db=new DatabaseSync(path);this.db.exec(`PRAGMA journal_mode=WAL;PRAGMA busy_timeout=5000;PRAGMA foreign_keys=ON;CREATE TABLE IF NOT EXISTS users(subject TEXT PRIMARY KEY,first_day TEXT NOT NULL,day TEXT NOT NULL,daily_used INTEGER NOT NULL DEFAULT 0,welcome_used INTEGER NOT NULL DEFAULT 0);CREATE TABLE IF NOT EXISTS receipts(subject TEXT NOT NULL REFERENCES users(subject) ON DELETE CASCADE,request_id TEXT NOT NULL,id TEXT NOT NULL UNIQUE,created_at INTEGER NOT NULL,cards TEXT NOT NULL,PRIMARY KEY(subject,request_id));CREATE TABLE IF NOT EXISTS sessions(hash TEXT PRIMARY KEY,subject TEXT NOT NULL REFERENCES users(subject) ON DELETE CASCADE,expires_at INTEGER NOT NULL);`);}
 atomic(fn){this.db.exec('BEGIN IMMEDIATE');try{const result=fn();this.db.exec('COMMIT');return result;}catch(e){this.db.exec('ROLLBACK');throw e;}}
 ensure(subject){const day=koreanDay(this.clock());this.db.prepare('INSERT OR IGNORE INTO users(subject,first_day,day) VALUES(?,?,?)').run(subject,day,day);this.db.prepare('UPDATE users SET day=?,daily_used=0 WHERE subject=? AND day<?').run(day,subject,day);return this.db.prepare('SELECT * FROM users WHERE subject=?').get(subject);}
 snapshot(user){const now=this.clock();const dailyRemaining=Math.max(0,1-user.daily_used),welcomeRemaining=koreanDay(now)===user.first_day?Math.max(0,2-user.welcome_used):0;return {day:user.day,dailyRemaining,welcomeRemaining,total:dailyRemaining+welcomeRemaining,nextResetAt:nextKoreanMidnight(now),serverTime:now,adsEnabled:false,adRemaining:0};}
 quota(subject){return this.atomic(()=>this.snapshot(this.ensure(subject)));}
 login(subject){return this.atomic(()=>{this.ensure(subject);const token=randomBytes(32).toString('base64url'),expiresAt=this.clock()+30*60*1000;this.db.prepare('DELETE FROM sessions WHERE expires_at<=?').run(this.clock());this.db.prepare('INSERT INTO sessions VALUES(?,?,?)').run(digest(token),subject,expiresAt);return {token,expiresAt};});}
 authenticate(token){if(typeof token!=='string'||token.length>200)throw new ServiceError('토스 로그인이 필요해요.',401);const row=this.db.prepare('SELECT subject FROM sessions WHERE hash=? AND expires_at>?').get(digest(token),this.clock());if(!row)throw new ServiceError('이용권을 다시 확인해 주세요.',401);return row.subject;}
 reserve(subject,requestId){if(typeof requestId!=='string'||!/^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(requestId))throw new ServiceError('요청 번호를 확인해 주세요.');return this.atomic(()=>{const user=this.ensure(subject),old=this.db.prepare('SELECT * FROM receipts WHERE subject=? AND request_id=?').get(subject,requestId);if(old)return {receipt:{id:old.id,requestId,createdAt:old.created_at,cardNumbers:JSON.parse(old.cards)},quota:this.snapshot(user),replayed:true};const quota=this.snapshot(user);if(quota.total<=0)throw new ServiceError('오늘 이용권을 모두 사용했어요. 한국 시간 자정에 1팩이 충전돼요.',429);const cardNumbers=this.draw();if(!Array.isArray(cardNumbers)||cardNumbers.length!==3||cardNumbers.some(id=>!/^E0(?:0[1-9]|[1-8][0-9]|9[0-6])$/.test(id)))throw new ServiceError('카드팩 생성에 실패했어요. 이용권은 차감되지 않았어요.',500);const receipt={id:randomUUID(),requestId,createdAt:this.clock(),cardNumbers};this.db.prepare('INSERT INTO receipts VALUES(?,?,?,?,?)').run(subject,requestId,receipt.id,receipt.createdAt,JSON.stringify(cardNumbers));this.db.prepare(quota.dailyRemaining?'UPDATE users SET daily_used=daily_used+1 WHERE subject=?':'UPDATE users SET welcome_used=welcome_used+1 WHERE subject=?').run(subject);return {receipt,quota:this.snapshot(this.ensure(subject)),replayed:false};});}
 unlink(subject){this.db.prepare('DELETE FROM users WHERE subject=?').run(subject);}
 close(){this.db.close();}
}
