import pg from 'pg';
import {randomBytes,createHash,randomUUID,randomInt} from 'node:crypto';
import {ServiceError,koreanDay,nextKoreanMidnight} from './ledger.mjs';
const {Pool}=pg;
const digest=value=>createHash('sha256').update(value).digest('hex');
function defaultDraw(){return Array.from({length:3},()=>{const r=randomInt(100),off=r<70?1:r<95?2:3;const i=randomInt(32);return `E${String(i*3+off).padStart(3,'0')}`;});}
export class PgLedger{
 constructor(url,{clock=Date.now,draw=defaultDraw}={}){this.clock=clock;this.draw=draw;this.pool=new Pool({connectionString:url,max:5});}
 async init(){await this.pool.query(`CREATE TABLE IF NOT EXISTS users(subject TEXT PRIMARY KEY,first_day TEXT NOT NULL,day TEXT NOT NULL,daily_used INTEGER NOT NULL DEFAULT 0,welcome_used INTEGER NOT NULL DEFAULT 0);CREATE TABLE IF NOT EXISTS receipts(subject TEXT NOT NULL REFERENCES users(subject) ON DELETE CASCADE,request_id TEXT NOT NULL,id TEXT NOT NULL UNIQUE,created_at BIGINT NOT NULL,cards JSONB NOT NULL,PRIMARY KEY(subject,request_id));CREATE TABLE IF NOT EXISTS sessions(hash TEXT PRIMARY KEY,subject TEXT NOT NULL REFERENCES users(subject) ON DELETE CASCADE,expires_at BIGINT NOT NULL);`);}
 snapshot(user){const now=this.clock();const dailyRemaining=Math.max(0,1-Number(user.daily_used)),welcomeRemaining=koreanDay(now)===user.first_day?Math.max(0,2-Number(user.welcome_used)):0;return {day:user.day,dailyRemaining,welcomeRemaining,total:dailyRemaining+welcomeRemaining,nextResetAt:nextKoreanMidnight(now),serverTime:now,adsEnabled:false,adRemaining:0};}
 async ensure(c,subject){const day=koreanDay(this.clock());await c.query('INSERT INTO users(subject,first_day,day) VALUES($1,$2,$2) ON CONFLICT(subject) DO NOTHING',[subject,day]);await c.query('UPDATE users SET day=$1,daily_used=0 WHERE subject=$2 AND day<$1',[day,subject]);const {rows}=await c.query('SELECT * FROM users WHERE subject=$1',[subject]);return rows[0];}
 async quota(subject){const c=await this.pool.connect();try{await c.query('BEGIN');const user=await this.ensure(c,subject);await c.query('COMMIT');return this.snapshot(user);}catch(e){await c.query('ROLLBACK');throw e;}finally{c.release();}}
 async login(subject){const c=await this.pool.connect();try{await c.query('BEGIN');await this.ensure(c,subject);const token=randomBytes(32).toString('base64url'),expiresAt=this.clock()+30*60*1000;await c.query('DELETE FROM sessions WHERE expires_at<=$1',[this.clock()]);await c.query('INSERT INTO sessions(hash,subject,expires_at) VALUES($1,$2,$3)',[digest(token),subject,expiresAt]);await c.query('COMMIT');return {token,expiresAt};}catch(e){await c.query('ROLLBACK');throw e;}finally{c.release();}}
 async authenticate(token){if(typeof token!=='string'||token.length>200)throw new ServiceError('토스 로그인이 필요해요.',401);const {rows}=await this.pool.query('SELECT subject FROM sessions WHERE hash=$1 AND expires_at>$2',[digest(token),this.clock()]);if(!rows[0])throw new ServiceError('이용권을 다시 확인해 주세요.',401);return rows[0].subject;}
 async reserve(subject,requestId){if(typeof requestId!=='string'||!/^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(requestId))throw new ServiceError('요청 번호를 확인해 주세요.');const c=await this.pool.connect();try{await c.query('BEGIN');await this.ensure(c,subject);let {rows:[user]}=await c.query('SELECT * FROM users WHERE subject=$1 FOR UPDATE',[subject]);const old=await c.query('SELECT * FROM receipts WHERE subject=$1 AND request_id=$2',[subject,requestId]);if(old.rows[0]){await c.query('COMMIT');const x=old.rows[0];return {receipt:{id:x.id,requestId,createdAt:Number(x.created_at),cardNumbers:x.cards},quota:this.snapshot(user),replayed:true};}const q=this.snapshot(user);if(q.total<=0)throw new ServiceError('오늘 이용권을 모두 사용했어요. 한국 시간 자정에 1팩이 충전돼요.',429);const cardNumbers=this.draw();if(!Array.isArray(cardNumbers)||cardNumbers.length!==3||cardNumbers.some(id=>!/^E0(?:0[1-9]|[1-8][0-9]|9[0-6])$/.test(id)))throw new ServiceError('카드팩 생성에 실패했어요. 이용권은 차감되지 않았어요.',500);const receipt={id:randomUUID(),requestId,createdAt:this.clock(),cardNumbers};await c.query('INSERT INTO receipts(subject,request_id,id,created_at,cards) VALUES($1,$2,$3,$4,$5::jsonb)',[subject,requestId,receipt.id,receipt.createdAt,JSON.stringify(cardNumbers)]);if(q.dailyRemaining)await c.query('UPDATE users SET daily_used=daily_used+1 WHERE subject=$1',[subject]);else await c.query('UPDATE users SET welcome_used=welcome_used+1 WHERE subject=$1',[subject]);({rows:[user]}=await c.query('SELECT * FROM users WHERE subject=$1',[subject]));await c.query('COMMIT');return {receipt,quota:this.snapshot(user),replayed:false};}catch(e){await c.query('ROLLBACK');throw e;}finally{c.release();}}
 async unlink(subject){await this.pool.query('DELETE FROM users WHERE subject=$1',[subject]);}
 async close(){await this.pool.end();}
}
